#!/bin/bash
cd ${OPENSHIFT_REPO_DIR}

ATTEMPT_MAX=1
ATTEMPT_NUM=1

log_end() {
  echo "***End sharepoint sync***" >> ${OPENSHIFT_LOG_DIR}/load-sharepoint.log
}

sp_load() {
  echo "***Begin sharepoint sync***" >> ${OPENSHIFT_LOG_DIR}/load-sharepoint.log
  date >> ${OPENSHIFT_LOG_DIR}/load-sharepoint.log
  echo "Attempt $ATTEMPT_NUM"
  echo "Attempt $ATTEMPT_NUM" >> ${OPENSHIFT_LOG_DIR}/load-sharepoint.log
  npm run load-sharepoint >> ${OPENSHIFT_LOG_DIR}/load-sharepoint.log
  LOGDATA="$(tail -n 1 ${OPENSHIFT_LOG_DIR}/load-sharepoint.log)"

  log_end
  if [ "$LOGDATA" == "  status: 504 }" ]; then
    echo "Timeout"
    if [ "$ATTEMPT_NUM" -ne "$ATTEMPT_MAX" ]; then
      ((ATTEMPT_NUM++))
      sp_load   # retry
    fi
  else
    echo "Possibly success"
  fi
}

if [ ! -z "$1" ]; then
  ATTEMPT_MAX=$1
fi

# run every 5 minutes
minute=$(date +%M)
if [ $(($minute % 5)) -eq 0 ]; then
  echo "Attempt sharepoint load $ATTEMPT_MAX times"
  sp_load
fi

